version: '3.5'

services:
  healthcenterstructuredomainservice.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      
  healthcenterstructuredomainservice.migration:
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://+:80
    - ConnectionStrings__Main=Host=database-postgres;Port=5432;database=health_center_structure;User Id=sa;Password=Qwerty123;

  appointmentdomainservice.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      
  appointmentdomainservice.migration:
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://+:80
    - ConnectionStrings__Main=Host=database-postgres;Port=5432;database=appointment;User Id=sa;Password=Qwerty123;

  healthmeasurementdomainservice.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      
  healthmeasurementdomainservice.migration:
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://+:80
    - ConnectionStrings__Main=Host=database-postgres;Port=5432;database=health_measurement;User Id=sa;Password=Qwerty123;

  webclientbffservice.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

  mobileclientbffservice.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

  videoconfintegrservice.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

  videoconfintegrservice.migration:
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://+:80
    - ConnectionStrings__Main=Host=database-postgres;Port=5432;database=video_conference;User Id=sa;Password=Qwerty123;

  healthcheckui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - HealthChecksUI__HealthChecks__0__Name=Health Center Structure Domain Service Health Check
      - HealthChecksUI__HealthChecks__0__Uri=http://healthcenterstructuredomainservice.webapi/health
      - HealthChecksUI__HealthChecks__1__Name=Appointment Domain Service Health Check
      - HealthChecksUI__HealthChecks__1__Uri=http://appointmentdomainservice.webapi/health
      - HealthChecksUI__HealthChecks__2__Name=Web Client BFF Service Health Check
      - HealthChecksUI__HealthChecks__2__Uri=http://webclientbffservice.webapi/health
      - HealthChecksUI__HealthChecks__3__Name=Mobile Client BFF Service Health Check
      - HealthChecksUI__HealthChecks__3__Uri=http://mobileclientbffservice.webapi/health
      - HealthChecksUI__HealthChecks__4__Name=Video Conference Integration Service Health Check
      - HealthChecksUI__HealthChecks__4__Uri=http://videoconfintegrservice.webapi/health
      - HealthChecksUI__HealthChecks__5__Name=Health Measurement Domain Service Health Check
      - HealthChecksUI__HealthChecks__5__Uri=http://healthmeasurementdomainservice.webapi/health
      - ui_path=/health