// <auto-generated />
using System;
using Telemedicine.Services.VideoConfIntegrService.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Telemedicine.Services.VideoConfIntegrService.MigrationEfCore.Migrations
{
    [DbContext(typeof(VideoConferenceIntegrationServiceDbContext))]
    [Migration("20220119063559_Version_1")]
    partial class Version_1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Telemedicine.Services.VideoConfIntegrService.Core.Entities.Conference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TimeSpan>("AppointmentDuration")
                        .HasColumnType("interval")
                        .HasColumnName("appointment_duration");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_id");

                    b.Property<DateTime>("AppointmentStartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("appointment_start_date");

                    b.Property<string>("AppointmentTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("appointment_title");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("FullExtension")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("full_extension");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    b.Property<string>("RoomPin")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("room_pin");

                    b.Property<string>("RoomUrl")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("room_url");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_on");

                    b.Property<string>("XmlResponse")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("xml_response");

                    b.HasKey("Id")
                        .HasName("pk_conference");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_conference_appointment_id")
                        .HasFilter("is_deleted = false");

                    b.ToTable("conference");
                });
#pragma warning restore 612, 618
        }
    }
}
